### ISSUE TITLE
怎么忽略某个字段

### ISSUE THREAD

**Issue by onXoot** [javaoffers/briefest#28]
### Current version
3.6.2

### How did the problem arise? (Make sure the latest version also has problems!!)
怎么像mybatis-plus 的     @TableField(exist = false) 一样忽略某个字段?

**Comment by javaofferss** [comment]
如果这个字段是表里面的字段则brief框架会自动映射, 如果不是表字段则会被默认忽略.  
当然如果想在select().colAll()忽略在表里已经映射好的字段,则可以使用@ColName('xxx', excludeColAll=true).

`
 /* CREATE TABLE `teacher` (
 *   `id` int(11) NOT NULL AUTO_INCREMENT,
 *   `name` varchar(255) COLLATE utf8_bin DEFAULT NULL,
 *   `status` int(2) DEFAULT NULL,
 *   PRIMARY KEY (`id`)
 * ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
 * /
@Data
@BaseModel
public class Teacher {
    @BaseUnique
    private Integer id;
    private String name;
    private RowStatus status;
   private String xxx; //这个字段会被自动忽略. 因为在teacher表中不存在.
    @ColName(value = "id", excludeColAll = true)
    private Long countId; //这个字段会在select().colAll()时自动排除
}
`

**Comment by javaofferss** [comment]
> ### Current version
> 
> 3.6.2
> ### How did the problem arise? (Make sure the latest version also has problems!!)
> 
> 怎么像mybatis-plus 的 @TableField(exist = false) 一样忽略某个字段?

请参考我上面说的, 不知道是否解决你的问题

**Comment by onXoot** [comment]
> > ### Current version
> > 3.6.2
> > ### How did the problem arise? (Make sure the latest version also has problems!!)
> > 怎么像mybatis-plus 的 @TableField(exist = false) 一样忽略某个字段?
> 
> 请参考我上面说的, 不知道是否解决你的问题

已解决 好用 感谢
