### ISSUE TITLE
3.6.3: java.lang.NoClassDefFoundError: org/reflections/Reflections

### ISSUE THREAD

**Issue by onXoot** [javaoffers/briefest#30]
### Current version
brief 3.6.3
jdk 17
spring boot 2.7.8

### How did the problem arise? (Make sure the latest version also has problems!!)
brief-common 里面的reflections 设置为了 compile ,导致运行时缺少 org.reflections.Reflections
```
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.9.12</version>
            <scope>compile</scope>
        </dependency>
```
### Error message
```
Caused by: java.lang.NoClassDefFoundError: org/reflections/Reflections
        at com.javaoffers.brief.modelhelper.utils.ReflectionUtils.<clinit>(ReflectionUtils.java:19)
        at com.javaoffers.brief.modelhelper.config.BriefProperties.initJqlFilters(BriefProperties.java:155)
        at com.javaoffers.brief.modelhelper.config.BriefProperties.freshAll(BriefProperties.java:102)
        at com.javaoffers.brief.modelhelper.speedier.BriefSpeedier.getInstance(BriefSpeedier.java:107)
```

### Your expectations 
删除 org.reflections 的 `<scope>compile</scope>`
### work around
手动添加org.reflections 依赖

**Comment by javaofferss** [comment]
> ### Current version
> 
> brief 3.6.3 jdk 17 spring boot 2.7.8
> ### How did the problem arise? (Make sure the latest version also has problems!!)
> 
> brief-common 里面的reflections 设置为了 compile ,导致运行时缺少 org.reflections.Reflections
> 
> ```
>         <dependency>
>             <groupId>org.reflections</groupId>
>             <artifactId>reflections</artifactId>
>             <version>0.9.12</version>
>             <scope>compile</scope>
>         </dependency>
> ```
> 
> ### Repeat steps
> ### Error message
> 
> ```
> Caused by: java.lang.NoClassDefFoundError: org/reflections/Reflections
>         at com.javaoffers.brief.modelhelper.utils.ReflectionUtils.<clinit>(ReflectionUtils.java:19)
>         at com.javaoffers.brief.modelhelper.config.BriefProperties.initJqlFilters(BriefProperties.java:155)
>         at com.javaoffers.brief.modelhelper.config.BriefProperties.freshAll(BriefProperties.java:102)
>         at com.javaoffers.brief.modelhelper.speedier.BriefSpeedier.getInstance(BriefSpeedier.java:107)
> ```
> 
> ### Your expectations
> 
> 删除 org.reflections 的 `<scope>compile</scope>`
> ### work around
> 
> 手动添加org.reflections 依赖

好的, 马上修复. 非常感谢您的issues.

**Comment by javaofferss** [comment]
> > ### Current version
> > brief 3.6.3 jdk 17 spring boot 2.7.8
> > ### How did the problem arise? (Make sure the latest version also has problems!!)
> > brief-common 里面的reflections 设置为了 compile ,导致运行时缺少 org.reflections.Reflections
> > ```
> >         <dependency>
> >             <groupId>org.reflections</groupId>
> >             <artifactId>reflections</artifactId>
> >             <version>0.9.12</version>
> >             <scope>compile</scope>
> >         </dependency>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Repeat steps
> > ### Error message
> > ```
> > Caused by: java.lang.NoClassDefFoundError: org/reflections/Reflections
> >         at com.javaoffers.brief.modelhelper.utils.ReflectionUtils.<clinit>(ReflectionUtils.java:19)
> >         at com.javaoffers.brief.modelhelper.config.BriefProperties.initJqlFilters(BriefProperties.java:155)
> >         at com.javaoffers.brief.modelhelper.config.BriefProperties.freshAll(BriefProperties.java:102)
> >         at com.javaoffers.brief.modelhelper.speedier.BriefSpeedier.getInstance(BriefSpeedier.java:107)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Your expectations
> > 删除 org.reflections 的 `<scope>compile</scope>`
> > ### work around
> > 手动添加org.reflections 依赖
> 
> 好的, 马上修复. 非常感谢您的issues.

已经释放 3.6.4 进行了修复.
